Importer: add replacements for deprecated getInstance
wpilibsuite/vscode-wpilib pull request #473
Opened 2021-10-30 20:02 UTC by sciencewhiz

2021-11-01 18:28 UTC, PeterJohnson approved these changes

2021-11-01 18:30 UTC, PeterJohnson requested changes

2021-11-01 18:30 UTC, PeterJohnson commented on vscode-wpilib/resources/cpp_replacements.json
> +      { "from": "wpi::SendableRegistry::GetInstance[(][)][.]", "to": "wpi::SendableRegistry::" },
Trailing comma needs to be removed.
```suggestion
      { "from": "wpi::SendableRegistry::GetInstance[(][)][.]", "to": "wpi::SendableRegistry::" }
```

2021-11-01 18:30 UTC, PeterJohnson commented on vscode-wpilib/resources/java_replacements.json
> +      { "from": "SendableRegistry[.]getInstance[(][)][.]", "to": "SendableRegistry." },
```suggestion
      { "from": "SendableRegistry[.]getInstance[(][)][.]", "to": "SendableRegistry." }
```

2021-11-02 03:16 UTC, sciencewhiz commented on vscode-wpilib/resources/cpp_replacements.json
> +      { "from": "wpi::SendableRegistry::GetInstance[(][)][.]", "to": "wpi::SendableRegistry::" },
interesting that it didn't fail

2021-11-02 16:00 UTC, PeterJohnson approved these changes

2021-11-05 07:22 UTC, merged