Add unit test config to settings.gradle for Java
wpilibsuite/vscode-wpilib pull request #476
Opened 2021-10-31 22:41 UTC by sciencewhiz

Adapted from https://www.chiefdelphi.com/t/unit-testing-java-io-ioexception-wpihaljni/372288/19

2021-11-01 18:35 UTC, PeterJohnson requested changes
Really the whole file needs a bit of reformatting, but fixed the additions.

2021-11-01 18:35 UTC, PeterJohnson commented on vscode-wpilib/resources/gradle/java/.vscode/settings.json
> +          "DYLD_LIBRARY_PATH": "${workspaceFolder}/build/jni/debug" }
Formatting
```suggestion
        "env": {
          "LD_LIBRARY_PATH": "${workspaceFolder}/build/jni/debug",
          "DYLD_LIBRARY_PATH": "${workspaceFolder}/build/jni/debug"
        }
```

2021-11-01 18:35 UTC, PeterJohnson commented on vscode-wpilib/resources/gradle/javadt/.vscode/settings.json
> +          "DYLD_LIBRARY_PATH": "${workspaceFolder}/build/jni/debug" }
```suggestion
        "env": {
          "LD_LIBRARY_PATH": "${workspaceFolder}/build/jni/debug",
          "DYLD_LIBRARY_PATH": "${workspaceFolder}/build/jni/debug"
        }
```

2021-11-01 18:35 UTC, PeterJohnson commented on vscode-wpilib/resources/gradle/javaromi/.vscode/settings.json
> +          "DYLD_LIBRARY_PATH": "${workspaceFolder}/build/jni/debug" }
```suggestion
        "env": {
          "LD_LIBRARY_PATH": "${workspaceFolder}/build/jni/debug",
          "DYLD_LIBRARY_PATH": "${workspaceFolder}/build/jni/debug"
        }
```

2021-11-01 19:01 UTC, sciencewhiz commented
This may also have to changed based on the resolution to #475

2021-11-07 23:15 UTC, PeterJohnson commented
Now that 480 has been merged, this just needs updating to point to release.

2021-11-07 23:37 UTC, ThadHouse approved these changes

2021-11-08 00:05 UTC, merged