Make UI vscode styled and refactor webview js
wpilibsuite/vscode-wpilib pull request #730
Opened 2024-12-09 00:06 UTC by GrahamSH-LLK

- Restyles UI to fit in with vscode
![image](https://github.com/user-attachments/assets/9c2d46e9-c777-4cfe-adc1-01b821bd6a44)
- Refactors the webview js
	- Previously, this used `innerHTML` to create the content and created eventListeners in another function based on DOM attributes. This refactors to create through `document.createElement`, giving access to the elements on creation so eventListeners can be created there (and version info captured)

2024-12-09 01:58 UTC, Gold856 requested changes
Minor formatting thing: I looked through the repo and determined this set of Prettier settings is the most consistent with the existing code. I'm considering doing a formatting job, so for consistency, these are the formatting settings you should use.
```json
{
    "singleQuote": true,
    "endOfLine": "crlf",
    "trailingComma": "es5"
}
```

2024-12-09 13:36 UTC, jasondaming commented
Can you explain more what you are trying to do with "figure out how to make the deps bundled"?

2024-12-09 13:59 UTC, GrahamSH-LLK commented
> Can you explain more what you are trying to do with "figure out how to make the deps bundled"?

 node_modules don’t exist in the built vsix, so the way I’m importing vscode-elements currently (uri from there) won’t work. I think I can get webpack to load the dependencies I need using raw-loader and inline as a script element. I’m open to other ideas, though!

2024-12-11 04:59 UTC, Gold856 approved these changes
Looks good to me

2024-12-16 01:22 UTC, PeterJohnson commented
Needs conflicts resolved.

2024-12-16 02:09 UTC, PeterJohnson commented
Build is failing

2024-12-16 02:42 UTC, sciencewhiz commented on vscode-wpilib/package.json
> +        "onCommand:wpilib.refreshVendordeps"
needs a comma

2024-12-16 02:47 UTC, sciencewhiz commented on vscode-wpilib/media/codicon.ttf
This appears to be licensed as CC BY 4.0 which needs attribution. https://github.com/microsoft/vscode-codicons?tab=readme-ov-file#legal-notices

2024-12-17 05:09 UTC, PeterJohnson approved these changes

2024-12-17 05:10 UTC, merged